### ISSUE TITLE
Locked out

### ISSUE THREAD

**Issue by ghost** [liip-elearning/moodle-block_disk_quota#6]
I am testing and I have exceeded the disk quota. The site does not log me in so I can delete data.
How can I proceed in these situations? The plugin does not allow login as an Admin.
![image](https://user-images.githubusercontent.com/9567680/73344623-f31a7300-4282-11ea-8987-8d827dcb581c.png)

**Comment by OdyX** [comment]
As the forced maintenance is set with the `enable_cli_maintenance_mode()` Moodle function, you need to remove the `dataroot/climaintenance.html` file, that will unlock your Moodle. It will likely get blocked again after a scheduled tasks run though.
